version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: drugstore_databases
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf  # Monta el archivo postgresql.conf
    networks:
      - drugstore-network

  flyway:
    image: flyway/flyway:8.0.2
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -password=root migrate
    volumes:
      - ./flyway/migrations:/flyway/sql
    networks:
      - drugstore-network

volumes:
  postgres_data:

networks:
  drugstore-network: