spring:
  application:
    name: user-service

  cloud:
    config:
      uri: http://localhost:8888
    netflix:
      eureka:
        client:
          enabled: true
          service-url:
            defaultZone: http://localhost:8761/eureka/
        instance:
          prefer-ip-address: true
          lease-renewal-interval-in-seconds: 10
          lease-expiration-duration-in-seconds: 30

  datasource:
    url: jdbc:postgresql://localhost:5431/drugstore_users_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8086

eureka:
  client:
    accept-header: application/json

management:
  endpoints:
    web:
      exposure:
        include: "*"

springCloudVersion: Hoxton.SR8

# JWT Secret Key
jwt:
  secret: U29tZSByYW5kb20gdGV4dCBzdHJpbmcgdG8gYmUgdXNlIGluIGFsbGlnb3JhdGggbmFtZXMgYW5kIGNvbnRleHQgaW4gYmFzZTY0IGNvZGUgaW4gcmVhZCBhdCB0aGUgZXh0cmEgZW5jb2Rpbmcu
