server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/alexistrejo/Documents/Java/API_Drugstore_Microservices/config-data